# Generated by Django 3.2.2 on 2021-08-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('page', models.IntegerField()),
                ('site', models.CharField(default='stackoverflow', max_length=20)),
                ('order', models.CharField(choices=[('desc', 'desc'), ('asc', 'asc')], default='desc', max_length=4)),
                ('sort', models.CharField(choices=[('activity', 'activity'), ('votes', 'votes'), ('creation', 'creation'), ('relevance', 'relevance')], default='activity', max_length=9)),
                ('closed', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=5)),
                ('accepted', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=5)),
                ('migrated', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=5)),
                ('wiki', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=5)),
            ],
        ),
    ]
