# Generated by Django 3.2.2 on 2021-08-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='accepted',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], max_length=5),
        ),
        migrations.AlterField(
            model_name='question',
            name='closed',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], max_length=5),
        ),
        migrations.AlterField(
            model_name='question',
            name='migrated',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], max_length=5),
        ),
        migrations.AlterField(
            model_name='question',
            name='wiki',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], max_length=5),
        ),
    ]
